booksproject/Books/models.py
from . import db

class Genre(db.Model):
    __tablename__ = 'genres'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'defaultgenre.jpg')
    books = db.relationship('Book', backref='Genre', cascade="all, delete-orphan")

    def __repr__(self):
        str = "Id: {}, Name: {}, Description: {}, Image: {} \n"
        str = str.format(self.id, self.name, self.description, self.image)
        return str

orderdetails = db.Table('orderdetails',
db.Column('order_id', db.Integer, db.ForeignKey('orders.id'), nullable=False),
db.Column('book_id', db.Integer, db.ForeignKey('books.id'), nullable=False),
db.PrimaryKeyConstraint('order_id', 'book_id'))


class Book(db.Model):
    __tablename__ = 'books'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False)
    price = db.Column(db.Float, nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    ISBN = db.Column(db.Integer, nullable=False)
    genre_id = db.Column(db.Integer, db.ForeignKey('genres.id'))

    def __repr__(self):
        str = "Id: {}, Name: {}, Description: {}, Image: {}, Price: {}, genres: {}, ISBN: {} \n"
        str = str.format(self.id, self.name, self.description,
                         self.image, self.price, self.genre_id, self.ISBN)
        return str


class Order(db.Model):
    __tablename__ = "orders"
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    firstname = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    totalcost = db.Column(db.Float)
    date = db.Column(db.DateTime)
    books = db.relationship("Book", secondary = orderdetails, backref="orders") 
    

    def __repr__(self):
        str = "id: {}, status: {}, Firstname: {}, Surname: {}, Email: {}, Phone: {}, Date: {}, Books: {}, Total Cost: {}\n"
        str = str.format(self.id, self.status, self.firstname, self.surname,
                         self.email, self.phone, self.date, self.books, self.totalcost)
        return str

booksproject/Books/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email

# checkout form


class CheckoutForm(FlaskForm):

    firstname = StringField("First name", validators=[InputRequired()])
    surname = StringField("Surname", validators=[InputRequired()])
    email = StringField("Email", validators=[InputRequired(), email()])
    phone = StringField("Phone Number", validators=[InputRequired()])
    submit = SubmitField("Submit")

booksproject/Books/__init__.py
#import flask - form package import class
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
app = Flask(__name__)


def create_app():

    app.debug = True

    app.secret_key = 'BetterSecretNeeded123'

    #app configuration for sql database
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///Booksberg.sqlite'

    #intialize db with flask app
    db.init_app(app)
    
    bootstrap = Bootstrap(app)

#registering blueprints
    from . import views
    app.register_blueprint(views.bp)
    from . import admin
    app.register_blueprint(admin.bp)
    return app


@app.errorhandler(404)
def not_found(e): 
    return render_template("404.html")


@app.errorhandler(500)
def internal_error(e):
    return render_template("500.html")

booksproject/Books/views.py
from flask import Blueprint, render_template, url_for, session, request, flash, redirect
from .models import Genre, Book, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db



bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    genres = Genre.query.order_by(Genre.name).all()
    return render_template('index.html', genres = genres)


@bp.route('/books/<int:genreid>/')
def genre_books(genreid):
    books = Book.query.filter(Book.genre_id == genreid)
    return render_template('genre_books.html', books = books)

@bp.route('/books')
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search)
    books = Book.query.filter(Book.description.like(search)).all()
    return render_template('genre_books.html', books = books)


#for order
@bp.route('/order/', methods=['POST', 'GET'])
def order():
    
    book_id = request.values.get('book_id')

    # retrive order if there is one
    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])

    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='',phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print("failed at creating new order")
            order = None

    #calculate total price
    totalprice =0 
    if order is not None:
        for book in order.books:
            totalprice = totalprice + book.price
    # adding any more items 
    if book_id is not None and order is not None:
        book = Book.query.get(book_id)
        if book not in order.books:
            try:
                order.books.append(book)
                db.session.commit()
            except:
                return "there was issue adding th item to basket"
            return redirect(url_for('main.order'))
        else:
            flash('itme already in basket')
            return redirect(url_for('main.order'))
    
    return render_template('order.html', order = order, totalprice = totalprice)

#for delete order
@bp.route('/deleteorder/')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))
    
#for delete single item
@bp.route('/deleteorderitem/', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        book_to_delete = Book.query.get(id)
        try:
            order.books.remove(book_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

#for checkout
@bp.route('/checkout/', methods=['POST', 'GET'])
def checkout():
    form = CheckoutForm()
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])

        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for book in order.books:
                totalcost = totalcost + book.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('thank you for providing details ! we will contact you shortly')
                return redirect(url_for('main.index'))
            except:
                return ' there was an issue completing your order'
    return render_template('checkout.html', form = form)

booksproject/Books/templates/505.html
{% extends 'base.html' %}

{% block main %}
<h1>Error 505 </h1>

<p>
    Sorry, but the server has encountered an error. Please try again in a few minutes.
</p>
{% endblock %}

booksproject/Books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<!--use this for leave comment-->

<head>
    <meta content ="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="description" content="Books Berg">
    <!-- Boostrap required meta-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BooksBerg</title>

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--jquery first, then popper.js and the boostrap.js-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <!-- for Css stylesheet-->
    <!--link rel="stylesheet" href="css/style.css"-->
    <style>
        .my-row {
            border: 1px solid grey;
        }
    </style>

</head>

<body>

    <!--contains the heading, navigation and banner image-->

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light bg-info">
            <!--div class="container"-->
            <!--travel app name or logo-->

            <a class="navbar-brand" href="{{url_for('main.index', _anchor='index_anchor')}}">Books Berg</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- navbar-->

            <div class="collapse navbar-collapse" id="navbarNav">

                <a class="nav-item nav-link text-dark"
                    href="{{url_for('main.index', _anchor='genre_anchor')}}">genres</a>

                <a class="nav-item nav-link text-dark" href="{{url_for('main.order')}}">Basket</a>

                <a class="nav-item nav-link text-dark" href="discount.html">discount Offers</a>

                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active">
                        <span class="navbar-text text-dark"> 1-800-80000 </span>
                    </li>
                    <li class="nav-item">
                        <form class="form-inline my-2 my-lg-0 ml-5" action="{{url_for('main.search')}}">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="=search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
        {% block head %}{% endblock %}
    </header>
    <!--- Content of main page -->
    <div class="container-fluid">
        <main>
            {% block main %}{% endblock %}
        </main>
    </div>

    <!--footer of the website-->
    <footer class="footer">
        <div class="container text-center ">
            <p>Copyright &copy; Books Berg 2020</p>
        </div>
    </footer>

</body>

</html>

booksproject/Books/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}


{% block head %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-primary" role="alert">
    {% for message in messages %}
    {{message}}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
{% endblock %}

{% block main %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Checkout</h1>
                <p>Please Provide your Required information. Thank you</p>

            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{wtf.quick_form(form)}}
            </div>
        </div>
    </div>
</section>
{% endblock %}

booksproject/Books/templates/genre_books.html
{% extends 'base.html' %}

{% block main %}
<section>
    <div class="text-dark text-center">
        <div>
            <p class="h3 text-dark mb-4">Select a book from below</p>
        </div>
    </div>

    <div class="card-columns">
        {% for book in books %}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='img/'+book.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{book.name}}</h4>
                <p class="card-text">{{book.description}}</p>
                <h5>{{"$%.2f"|format(book.price)}}</h5>
            </div>
            <div class="card-footer"><a href="{{ url_for('main.order', book_id=book.id) }}" class="btn btn-primary">Add
                    to Basket</a></div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

booksproject/Books/templates/index.html
{% extends 'base.html' %}
{% block head %}
<div class="jumbotron jumbotron-fluid card card-image" style="background-image: url({{url_for('static', filename= 'img/book_bg.jpg')}});">

    <div class="text-white text-center py-5 px-4">
        <div>
            <h1 class="display-2">Welcome to BooksBerg</h1>
            <p class="display-4 text-dark">Humans Best Friend</p>
        </div>
    </div>
    {% endblock %}
 
    {% block main %}
    <section>
        <div class="container">
            <div class="text-dark text-center">
                <div>
                    <p class="h1 text-dark mb-4">What we Have?</p>
                </div>
            </div>

            <div class="col-md-4">
                <article>
                    <h2>What we Offer !</h2>
                    <p>Beautiful stories</p>
                    <ul>
                        <li>Affordablle Prices</li>
                        <li>Best Selling books </li>
                        <li>Adventure and Fun</li>
                    </ul>

                </article>
            </div>

            <div class="col-md-4">
                <article>
                    <h2>Affordable selection</h2>
                    <p>we have great prices and with Exclusive Offers!</p>
                    <p>Click <a href="discount.html">here</a> for more information</p>
                </article>
            </div>
        </div>
    </section>


    <section>
        <div class="text-dark text-center">
            <div>
                <p class="h3 text-dark mb-4" id="genres_anchor">Pick a genre you like </p>
            </div>
        </div>

        <div class="card-columns">
            {% for genre in genres %}
            <div class="Card">
                <img class="card-img-top" src="{{url_for('static', filename= 'img/'+genre.image)}}" alt="Card image">
                <div class="card-body">
                    <h4 class="card-title">{{genre.name}}</h4>
                    <p class="card-text">{{genre.description}}</p>
                </div>
                <div class="card-footer"><a href="{{ url_for('main.genre_books',genreid=genre.id) }}"
                        class="btn btn-primary">Books</a></div>
            </div>
            {% endfor %}
        </div>
    </section>
    {% endblock %}

booksproject/Books/templates/order.html
{% extends 'base.html' %}

{% block main %}

<section>
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3>Your book Cart</h3>
        </div>

        {% for book in order.books %}
        <div class="row shadow-md my-row mb-3">
            <div class="col-sm-10 card">
                <h5 class="card-header">{{book.ISBN}} : {{book.name}} , {{book.Genre.name}}</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <img class="img-thumbnail" src="{{url_for('static',filename=('img/'+ book.image))}}">

                        </div>
                        <div class="col-10">
                            <p class="card-text">{{book.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>

            <div class="col-sm-2">
                <h5>{{"$%.2f"|format(book.price)}}</h5>
                <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                    <input type="hidden" id="id" name="id" value="{{book.id}}">
                    <input type="submit" value="Delete" class="btn btn-primary mb-3">
                </form>
            </div>

        </div>
        {% endfor %}

        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4">Total Cost = {{ "$%.2f"|format(totalprice) }}</h5>
            </div>
            <p> Gst prices are included**</p>

            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{ url_for('main.index', _anchor='genre_anchor')}}" class="btn btn-primary mr-4">Add More
                    books</a>
                <a href="{{url_for('main.deleteorder')}}" class="btn btn-primary mr-4">Clear Basket</a>

                <a href="{{url_for('main.checkout')}}" style="float: right" class="btn btn-primary mr-4">Continue Checkout</a>

            </div>
        </section>
    </div>
</section>
{% endblock %}